apiVersion: skaffold/v2beta24
kind: Config
build:
  artifacts:
  - image: node-example
    context: .
deploy:
  kubectl:
    manifests:
    - "k8s/*.yaml"
    hooks:
      after:
        - host:
            command: ["sh", "-c", "kubectl get ksvc node -o jsonpath='{.status.url}\n'"]
profiles:
- name: dev
  activation:
  - command: dev
  build:
    artifacts:
    - image: node-example
      context: .
      sync:
        infer:
        - src/**/*.js
      docker:
        buildArgs:
          ENV: development
- name: knative
  build:
    artifacts:
    - image: node-example
      context: .
      sync:
        infer:
        - src/**/*.js
      docker:
        buildArgs:
          ENV: development
  patches:
    - op: replace
      path:  /deploy/kubectl/manifests/0
      value: ".devops/knative/service.yaml"
- name: dev-knative
  build:
    artifacts:
    - image: node-example
      context: .
      sync:
        infer:
        - src/**/*.js
      docker:
        buildArgs:
          ENV: development
  patches:
    - op: replace
      path:  /deploy/kubectl/manifests/0
      value: ".devops/knative/service-debug.yaml"
    - op: replace
      path:  /portForward/0/resourceName
      value: "node-00001-deployment"
portForward:
  - resourceType: deployment
    resourceName: node
    port: 9229