apiVersion: skaffold/v2beta24
kind: Config
build:
  artifacts:
  - image: node-example
    context: .
deploy:
  kubectl:
    manifests:
    - ".devops/k8s/*.yaml"
    hooks:
      after:
        - host:
            command: ["sh", "-c", "kubectl get ksvc node -o jsonpath='{.status.url}\n' || true"]
profiles:
- name: dev
  activation:
  - command: dev
  build:
    artifacts:
    - image: node-example
      context: .
      sync:
        infer:
        - src/**/*.js
      docker:
        buildArgs:
          ENV: development
  patches:
    - op: remove
      path: /portForward/1
- name: knative
  build:
    artifacts:
    - image: node-example
      context: .
      sync:
        infer:
        - src/**/*.js
      docker:
        buildArgs:
          ENV: development
  patches:
    - op: replace
      path:  /deploy/kubectl/manifests/0
      value: ".devops/knative/service.yaml"
- name: knative-debug
  build:
    artifacts:
    - image: node-example
      context: .
      sync:
        infer:
        - src/**/*.js
      docker:
        buildArgs:
          ENV: development
  patches:
    - op: replace
      path:  /deploy/kubectl/manifests/0
      value: ".devops/knative/service-debug.yaml"
portForward:
  - resourceType: service
    resourceName: node-dev
    port: 8080
  - resourceType: service
    resourceName: node-dev
    port: 9229
