apiVersion: skaffold/v2beta24
kind: Config
build:
  artifacts:
  - image: node-example
    context: backend
deploy:
  kubectl:
    manifests:
    - "k8s/*.yaml"
profiles:
- name: dev
#  activation:
#  - command: dev
  build:
    artifacts:
    - image: node-example
      context: backend
      sync:
        infer:
        - src/**/*.js
      docker:
        buildArgs:
          ENV: development
- name: dev-knative
  build:
    artifacts:
    - image: node-example
      context: backend
      sync:
        infer:
        - src/**/*.js
      docker:
        buildArgs:
          ENV: development
  patches:
    - op: replace
      path:  /deploy/kubectl/manifests/0
      value: "knative/service.yaml"
- name: dev-knative-debug
  build:
    artifacts:
    - image: node-example
      context: backend
      sync:
        infer:
        - src/**/*.js
      docker:
        buildArgs:
          ENV: development
  patches:
    - op: replace
      path:  /deploy/kubectl/manifests/0
      value: "knative/service-debug.yaml"
portForward:
  - resourceType: deployment
    resourceName: node-00001-deployment
    port: 9229