apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node
spec:
  rules:
  - host: "hello.example.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: node
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-dev
spec:
  ports:
  - port: 8080
    name: http
  - port: 9229
    name: dbg
  type: LoadBalancer
  selector:
    app: node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: node-example
        ports:
        - containerPort: 8080
