apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: node
spec:
  template:
    metadata:
        annotations:
          autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: node-example